### ISSUE TITLE
Kind request to expand on installation and usage

### ISSUE THREAD

**Issue by convergentist** [ruizdiazever/portfolio-rs#1]
Hello sir, respect for the work you did, it is truly interesting and complete / full with functionality. 

Would it be possible to add an installation process ?, in the sense of a step-by-step or list of actions to setup everything. 

If I may, I would like to take your website as a template for mine. The intention is to build it with github pages

**Comment by ruizdiazever** [comment]
Hello, thanks Francisco!

My portfolio is a SSR app of Leptos, it is not possible to deploy to GitHub Pages!

Info about [Deploying a Full-Stack SSR App](https://book.leptos.dev/deployment/ssr.html#deploying-a-full-stack-ssr-app) by Leptos

If you are referring only to the UI, it may not be as convenient as a template since it is embedded in fragmented Rust code!
